### ISSUE TITLE
Datetimepicker does not work correctly in IE 11

### ISSUE THREAD

**Issue by Robin-Hoodie** [zhaber/angular-js-bootstrap-datetimepicker#100]
Selecting the time is not possible, the time does not get set in the model.

Only occurs on IE11, most likely because it does not support XPath, getting the following error:

`XPathResult not found`

Found the problem on line 186

`element[0], null, XPathResult.FIRST_ORDERED_NODE_TYPE, null).singleNodeValue;`

**Comment by zhaber** [comment]
IE is not a supported browser.

**Comment by Robin-Hoodie** [comment]
That's odd, is this documented anywhere?
