### ISSUE TITLE
Timezone issues

### ISSUE THREAD

**Issue by bestxp** [zhaber/angular-js-bootstrap-datetimepicker#101]
When i select  01-01-2016 12-00 in model passed  2015-12-31T21:00:00.000Z this is very bad mistake, please correct this timezone in directive must be as PC or this options is configurable

**Comment by zhaber** [comment]
See https://github.com/zhaber/angular-js-bootstrap-datetimepicker/issues/31

**Comment by narcotjke** [comment]
Datetimepicker does always return UTC time?
