### ISSUE TITLE
Create a new version tag please

### ISSUE THREAD

**Issue by isaacplmann** [zhaber/angular-js-bootstrap-datetimepicker#103]
Bower only pulls the latest tag in your repository, not the latest commit.  So I can't access the fix that you merged in from PR #96.  I noticed you updated the nuget version to 1.2.4.1.  Maybe you could make a github tag with the same number.

Thanks.

**Comment by zhaber** [comment]
Done https://github.com/zhaber/angular-js-bootstrap-datetimepicker/releases/tag/v1.2.4.1

**Comment by isaacplmann** [comment]
Thanks!
