### ISSUE TITLE
Emptying hour input resets date

### ISSUE THREAD

**Issue by Hypocrite** [zhaber/angular-js-bootstrap-datetimepicker#106]
When user clears the hour in timepicker it resets the selected date.

Steps to reproduce:

1. Select a different date than the default one.
2. Put an empty value to the hour input.
3. Date is reset to default from the selected value.

This happens only with the hour input but not with the minute input.

Happens also in the Plunker: http://plnkr.co/edit/HyGjgy?p=preview

**Comment by zhaber** [comment]
The bug was caused by https://github.com/zhaber/angular-js-bootstrap-datetimepicker/commit/af03a7d0a9f93d5eb22b25612ca56f5a0fb90af6#diff-11e8d851f57265d26823b90c8f465a4c Reverted the change in the last revision: http://plnkr.co/edit/HyGjgy?p=preview
