### ISSUE TITLE
Replace 'ngDisabled' with 'readonly' for "readonlyDate" property

### ISSUE THREAD

**Issue by nazar-kuzo** [zhaber/angular-js-bootstrap-datetimepicker#107]
Use case: I have date time picker popup where i don`t want to allow user to type the date but just select it from popup when he/she clicks on date field.
Actual: With "readonlyDate" it denies click event and changes cursor.
Expected: User cannot type the date in input but when he/she put focus on input - popup is shown.

I would suggest to keep both properties "readonlyDate", "disabledDate" but give semantics to them:
readonly date behaves as field with readonly attribute and disabled date behaves as field with disabled attribute.

**Comment by zhaber** [comment]
angular-js-bootstrap-datetimepicker is a wrapper around Angular ui datepicker, please submit this as a feature request at https://github.com/angular-ui/bootstrap/issues/new

**Comment by nazar-kuzo** [comment]
According to 
datetimepicker.js, line 110  ... ["ngDisabled", "readonlyDate"]
you are adding ng-disabled attribute to date picker template and it is not a bridge to existing angular-ui feature called "readonly date or disabled date" that puts ng-disabled attribute on date picker.

**Comment by zhaber** [comment]
I changed the behavior of readonly-date attribute to ng-readonly and added disabled-date attribute that maps to ng-disabled: http://plnkr.co/edit/HyGjgy?p=preview

**Comment by nazar-kuzo** [comment]
Thanks
