### ISSUE TITLE
Provide property "show-button-bar" which exists in Angular.UI Datepicker Popup

### ISSUE THREAD

**Issue by nazar-kuzo** [zhaber/angular-js-bootstrap-datetimepicker#108]
Please provide property "show-button-bar" which exists in Angular.UI Datepicker Popup which enables developer to hide/show bottom button bar when date picker popup is show.

**Comment by zhaber** [comment]
Done http://plnkr.co/edit/HyGjgy?p=preview

**Comment by nazar-kuzo** [comment]
Cool,

Thanks a lot!
