### ISSUE TITLE
Model change event event is not triggered when you change time only.

### ISSUE THREAD

**Issue by nazar-kuzo** [zhaber/angular-js-bootstrap-datetimepicker#109]
Use case: Implement Time range with two datetime pickers like StartDate/EndDate where StartDate picker will have dynamically changed maxDate dependent on currently selected date in EndDate picker  and EndDate picker will have dynamically changed minDate dependent on currently selected date in StartDate picker.

Actual: It works as expected but only when you choose date from datepicker popup, it means that min/max range is updated, but when you change the time - range is not updated.

Expected: Provide same range update when you changing date or time.

Hint: "$scope.time_change" event doesn`t update model with new like but calls "setHours" method, we need to explicitly update model like "$scope.ngModel = new Date(updatedModel);" in "$scope.time_change" event to trigger change event.

**Comment by zhaber** [comment]
Are you using deep watch on the date object, i.e. pass true as the third parameter of the watch function?

**Comment by nazar-kuzo** [comment]
There are no watch functions, simple definition below describes actual result of datetimepicker behavior. It updates min/max range according to current start/end date picker but doesn`t updated if I use time picker. Code in hint is from your framework implementation.

<datetimepicker 
name="MaintenanceStartDateTime"
ng-model="maintenanceStartDateTime"
date-format="MMM dd, yyyy"
date-options="{ minDate: minDate, maxDate: maintenanceEndDateTime }"
></datetimepicker>

<datetimepicker 
name="MaintenanceEndDateTime"
ng-model="maintenanceEndDateTime"
date-format="MMM dd, yyyy"
date-options="{ minDate: maintenanceStartDateTime, maxDate: maxDate }"
></datetimepicker>

**Comment by zhaber** [comment]
do you have a plunker where this issue can be reproduced?

**Comment by nazar-kuzo** [comment]
http://plnkr.co/edit/CIsnyR3HnGn3IAraFC2d?p=preview

As you will see the idea is to create datetime range and it works correctly when you are updating date from picker (min/max dates are updating).

But when you will choose the same date for both pickers and try to create time range in hours it wont updated min/max time for other time picker.

Just try to add 1 hour to maintenance end time and you`ll notice that maintenance start hours time picker is still disabled but it supposed to be enabled cause range becomes more that one hour.

**Comment by zhaber** [comment]
The underlying timepicker directive does not support changes on min/max without creating a new Date object. You can reproduce it at http://plnkr.co/edit/6f2volwKzPhBQ06vPXHn?p=preview Please feel free to file an issue against Angular UI and link it here https://github.com/angular-ui/bootstrap/issues/new

**Comment by nazar-kuzo** [comment]
You are absolutely right!

Thats why I provided some hint in description.

Hint: "$scope.time_change" event doesn`t update model with new like but calls "setHours" method, we need to explicitly update model like "$scope.ngModel = new Date(updatedModel);" in "$scope.time_change" event to trigger change event.

It would be great if you could do this improvement in your event listener. 
From my side, I`ll also duplicate this issue on angular-ui github.

**Comment by zhaber** [comment]
This workaround has other side-effects and makes code more convoluted, the bug you've found should be fixed at the source of the problem.

**Comment by nazar-kuzo** [comment]
Thanks
