### ISSUE TITLE
Please update NuGet package with latest version Source Code

### ISSUE THREAD

**Issue by nazar-kuzo** [zhaber/angular-js-bootstrap-datetimepicker#110]

**Comment by zhaber** [comment]
Here is version 1.2.4.1 https://www.nuget.org/packages/Angular-js-bootstrap-datetimepicker/

**Comment by nazar-kuzo** [comment]
Such error occurs when I try to install this package:

Could not install package 'Angular-js-bootstrap-datetimepicker 1.2.4.1'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5.2', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

Any ideas how to fix that?

**Comment by nazar-kuzo** [comment]
Any updates on that?

**Comment by zhaber** [comment]
I reassembled the package using a command line nuget and re-uploaded it to https://www.nuget.org/packages/Angular-js-bootstrap-datetimepicker/

$ nuget install Angular-js-bootstrap-datetimepicker
Feeds used:
  https://api.nuget.org/v3/index.json

  GET https://api.nuget.org/v3/registration1-gz/angular-js-bootstrap-datetimepicker/index.json
  OK https://api.nuget.org/v3/registration1-gz/angular-js-bootstrap-datetimepicker/index.json 235ms
Attempting to gather dependency information for package 'Angular-js-bootstrap-datetimepicker.1.3.3' with respect to project 'C:\Vitalii', targeting 'Any,Version=v0.0'
Attempting to resolve dependencies for package 'Angular-js-bootstrap-datetimepicker.1.3.3' with DependencyBehavior 'Lowest'
Resolving actions to install package 'Angular-js-bootstrap-datetimepicker.1.3.3'
Resolved actions to install package 'Angular-js-bootstrap-datetimepicker.1.3.3'
Adding package 'Angular-js-bootstrap-datetimepicker.1.3.3' to folder 'C:\Vitalii'
Added package 'Angular-js-bootstrap-datetimepicker.1.3.3' to folder 'C:\Vitalii'
Successfully installed 'Angular-js-bootstrap-datetimepicker 1.3.3' to C:\Vitalii

**Comment by davidetundo** [comment]
Hi,
I have the same problem with version 1.3.3

"Could not install package 'Angular-js-bootstrap-datetimepicker 1.3.3'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.6.1', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author."


Can you help me?
