### ISSUE TITLE
readonly-date bug

### ISSUE THREAD

**Issue by MarcelBuian** [zhaber/angular-js-bootstrap-datetimepicker#111]
##### Bug description:
When readonly-date is setted to true it's allows me to click on date (appears calendar) and even to change it.
##### Link to minimally-working plunker that reproduces the issue: 
http://plnkr.co/edit/twf6ig?p=preview

using version 1.3.3

**Comment by zhaber** [comment]
As per documentation, read-only means a user can't type inside the field
https://github.com/zhaber/angular-js-bootstrap-datetimepicker Try disabled-date to achieve the behaviour you are expecting.
