### ISSUE TITLE
NPM package should depend on angular-ui-bootstrap, and be re-published

### ISSUE THREAD

**Issue by jrharshath** [zhaber/angular-js-bootstrap-datetimepicker#112]
##### Bug description:
At the moment, the package.json lists "angular-bootstrap>=1.2.4" as its dependency. When trying to npm-install it, the following warning is shown, and then installation fails:

    npm WARN install Couldn't install optional dependency: No compatible version found: angular-bootstrap@>=0.14.0

It should be noted that [angular-bootstrap](https://www.npmjs.com/package/angular-bootstrap) was last published 11 months ago and its latest version on npm is only 0.12.2. However, [angular-ui-bootstrap](https://www.npmjs.com/package/angular-ui-bootstrap) was last published a month ago and its latest version is 1.3.3. So it definitely looks like we're linked to the wrong npm package.

(Bower does not suffer from the same problem - bower has both packages, and one is an [alias of the other](https://github.com/angular-ui/bootstrap-bower).)

**Comment by zhaber** [comment]
Republished the npm package https://www.npmjs.com/package/angular-ui-bootstrap-datetimepicker
