### ISSUE TITLE
"date-options" should be optional

### ISSUE THREAD

**Issue by jrharshath** [zhaber/angular-js-bootstrap-datetimepicker#113]
##### Bug description:
When `datetimepicker` is not supplied with a date-options object, it throws errors when the date selector is triggered by clicking the date field.

##### Link to minimally-working plunker that reproduces the issue: 
[Plunk is here.](http://plnkr.co/edit/mpiDWavtyYNpbSW35QCa?p=preview)

**Comment by zhaber** [comment]
ui-bootstrap requires angular 1.4.4. I updated the dependency version in datetimepicker accordingly.

**Comment by jrharshath** [comment]
Thanks! Could this update be published to npm as the an incremental patch version (v1.2.5)?

**Comment by zhaber** [comment]
Created v1.4.0 https://www.npmjs.com/package/angular-ui-bootstrap-datetimepicker

**Comment by jrharshath** [comment]
Great 👍
