### ISSUE TITLE
"ng-change" should be supported

### ISSUE THREAD

**Issue by jrharshath** [zhaber/angular-js-bootstrap-datetimepicker#114]
##### Bug description:
Most input elements that have ng-model also support `ng-change`. We should support that in angular-js-bootstrap-datetimepicker as well.

**Comment by zhaber** [comment]
A pull request is pending on addressing a minor comment: https://github.com/zhaber/angular-js-bootstrap-datetimepicker/pull/115/files#diff-11e8d851f57265d26823b90c8f465a4cR195

**Comment by jrharshath** [comment]
addressed it :) Lemme know if we need any other changes before we can merge this.
