### ISSUE TITLE
TypeError: Cannot read property '$error' of undefined

### ISSUE THREAD

**Issue by ilyassa** [zhaber/angular-js-bootstrap-datetimepicker#119]
##### Bug description:
When directive is removing from the DOM I got an error:
TypeError: Cannot read property '$error' of undefined

It happens because watchExpression in a $watch tries to operate with a property of an undefined object.
The scope.datetimepickerForm is undefined but watchExpression tries to return  scope.datetimepickerForm.$error

This situation concerns $dirty and timepicker.$touched expressions as well.

**Comment by zhaber** [comment]
Does the latest commit work for you? https://github.com/zhaber/angular-js-bootstrap-datetimepicker/commit/0e9a08062b57488e9ba4ba524abbefa6b3dd4cd1

**Comment by zhaber** [comment]
Added undefined check https://github.com/zhaber/angular-js-bootstrap-datetimepicker/commit/7dc2324968967f48dff83be17efe8ec6db463d97
