### ISSUE TITLE
Time is not shown with angular 1.5.8 and ui-bootstrap 2.0.*

### ISSUE THREAD

**Issue by dautushenka** [zhaber/angular-js-bootstrap-datetimepicker#120]
##### Bug description:
http://plnkr.co/edit/OEaicM?p=preview

**Comment by zhaber** [comment]
Datetime picker v1 is not compatible with ui-bootstrap 2.0, but you can try the latest version of the plugin: http://plnkr.co/edit/tCpIp0fQAY4Vuj8Krue1?p=preview (just published)

**Comment by aitboudad** [comment]
@zhaber could you please publish a new version on `npm` ?

**Comment by zhaber** [comment]
done

**Comment by dautushenka** [comment]
@zhaber 
Could you also update bower dependencies to "angular-bootstrap": "~1.3.3" for 1.x

**Comment by zhaber** [comment]
are there any limitations of 1.2.4?
