### ISSUE TITLE
Support for min and max to timepicker?

### ISSUE THREAD

**Issue by HeIsHuaxi** [zhaber/angular-js-bootstrap-datetimepicker#121]
This is not really a bug but it will be very helpful if we can configure the min and max for timepicker as well. Thanks!

**Comment by zhaber** [comment]
The minDate property in date-options controls what is the minimum value of date + time. Are you suggesting that time should be chose-able only from a particular interval? What use case are you trying to address? Pull requests for new features are welcome.

**Comment by zhaber** [comment]
I added min/max time attributes that control the minimum and maximum timepicker value. See http://plnkr.co/edit/uJm8PVq5kbRSmDZdlHpS?p=preview

**Comment by HeIsHuaxi** [comment]
@zhaber Thanks for the update, I will give it a try!

**Comment by HeIsHuaxi** [comment]
@zhaber The use case is I want to also be able to control the minimum and maximum value for the timepicker, say an interval of 2pm to 5pm.

**Comment by zhaber** [comment]
Do you have a case when max/min time do not work?
https://github.com/zhaber/angular-js-bootstrap-datetimepicker/blob/master/README.md

**Comment by HeIsHuaxi** [comment]
@zhaber Oh nice I didn't notice the update on the documentation. Will let you know if I see any issues. Thanks for adding the support!
