### ISSUE TITLE
Installing 2.0.1 through bower gives you 1.4.0

### ISSUE THREAD

**Issue by szwajkowski** [zhaber/angular-js-bootstrap-datetimepicker#124]
##### Bug description:
When you install with bower:
`bower install angular-ui-bootstrap-datetimepicker --save`
It saves as 2.0.1 but sources are from 1.4.0, this is because tag v2.0.1 does not contain commit https://github.com/zhaber/angular-js-bootstrap-datetimepicker/commit/1b00158c1e53b8b1b4985bb0cf22daaeabf0d5b7

@zhaber can you please fix it?

**Comment by zhaber** [comment]
Try now

**Comment by szwajkowski** [comment]
it still installs old tag 2.0.1 instead of 2.0.1.1 because bower is using [semver.org](semver.org) for versioning

**Comment by zhaber** [comment]
how about now

**Comment by szwajkowski** [comment]
now it works fine, thanks
