### ISSUE TITLE
Problem with date binding

### ISSUE THREAD

**Issue by Valerio81** [zhaber/angular-js-bootstrap-datetimepicker#125]
Hi,
I have this JSON from backend
`[{"parameterName":"@test","parameterType":"datetime","parameterValue":"2016-09-05T10:34:31.1106788Z","parameterLength":null,"parameterDescription":"Inserisci la data"},{"parameterName":"@test2","parameterType":"int","parameterValue":0,"parameterLength":null,"parameterDescription":"inserisci l\u0027intero"}]`
When page is loaded and binded with this JSON, datetimepicker is not correctly binded (I am in UTC +02:00 timezone)
![image](https://cloud.githubusercontent.com/assets/16916271/18245589/5bbd2b22-7366-11e6-8751-19b87b914cc8.png)

**Comment by zhaber** [comment]
Please provide a plunker where I can reproduce the problem. http://plnkr.co/edit/s6Gm8x8ExndUj6EBYbhi?p=preview

**Comment by Valerio81** [comment]
Here the plunker

http://plnkr.co/edit/GYcsRL

**Comment by zhaber** [comment]
It's expected for the string to be Date. You can try the latest version that supports string input but the output will be still Date.

**Comment by Valerio81** [comment]
Thank you very much.
