### ISSUE TITLE
On-change should fire when changing time, not just date

### ISSUE THREAD

**Issue by jdforsythe** [zhaber/angular-js-bootstrap-datetimepicker#126]
##### Bug description:

on-change function fires when selecting a different date (by clicking OR typing), but does not fire when choosing a different time, by clicking the spinners or typing, or changing am/pm.
##### Link to minimally-working plunker that reproduces the issue:

http://plnkr.co/edit/Yvlju9zbjIS9t1GydmfU?p=preview

**Comment by zhaber** [comment]
I updated the newest version with a fix.

**Comment by MGouaillier** [comment]
Hello.
Is this available ?

**Comment by zhaber** [comment]
It was released as v2.0.3 https://github.com/zhaber/angular-js-bootstrap-datetimepicker/releases/tag/2.0.3
