### ISSUE TITLE
"Date" menu don't close with multiple datetimepicker

### ISSUE THREAD

**Issue by stiix13** [zhaber/angular-js-bootstrap-datetimepicker#127]
When multiple datetimepicker on a form, if I open one and click in another one, the first doesn't close. To close them I need to click elsewhere on the document.

see http://plnkr.co/edit/rvb6ByQuzHHz1y3Uatnq

**Comment by zhaber** [comment]
Each datepicker is independent of the other ones, so in this case, you will need to programmatically close the datepicker using date-opened attribute. See https://github.com/zhaber/angular-js-bootstrap-datetimepicker and https://github.com/angular-ui/bootstrap/issues/3432
