### ISSUE TITLE
Choose output format

### ISSUE THREAD

**Issue by stiix13** [zhaber/angular-js-bootstrap-datetimepicker#128]
I'm sorry if i'm not in the right place to post this.

Is there a way to choose the output format? I believe right now the output format is only Date, but doesn't this would be better to allow an option to choose? Like  "dd/MM/YYY" or something like that?
Thanks for your work

**Comment by zhaber** [comment]
See `date-format` attribute at https://github.com/zhaber/angular-js-bootstrap-datetimepicker/blob/master/README.md
