### ISSUE TITLE
minDate and maxDate difference of behaviour

### ISSUE THREAD

**Issue by MGouaillier** [zhaber/angular-js-bootstrap-datetimepicker#129]
Hi !
I noticed a bug (not sure it's a bug) while using this picker (which is great by the way :D)
If you set a minDate and maxDate, when the picker has this limit selected it doesn't have the same behaviour.

Let me explain this with some pictures

**minDate is reached**
![image](https://cloud.githubusercontent.com/assets/19687884/20628942/4bd19e16-b329-11e6-97c8-c04d0e1e4727.png)
_There's a red ribbon around the time selection but you can still edit the time_

**maxDate is reached**
![image](https://cloud.githubusercontent.com/assets/19687884/20628956/5f2050de-b329-11e6-9c86-adbeb8c8023b.png)
_The time input is disabled_

This is quite annoying when you're using the picker without the little arrows that allow you to change the time, beacause you can't adjust the time in the maxDate case

**Comment by zhaber** [comment]
Datetimepicker is a composition of two directives: Angular UI Bootstrap date picker and time picker. Timepicker has the behavior you are describing and datetimepicker inherits it: https://plnkr.co/edit/4utIQRBX6VVBBsEmjshE?p=preview
Please file an issue against Angular UI Bootsrap to find if this can be addressed.
 
A similar request:
https://github.com/angular-ui/bootstrap/issues/6269
https://github.com/angular-ui/bootstrap/pull/6270

**Comment by MGouaillier** [comment]
I managed to fix this issue.

See https://github.com/angular-ui/bootstrap/issues/6337
