### ISSUE TITLE
v2.0.2 is not on npm, causing problems due to the version check

### ISSUE THREAD

**Issue by wraithan** [zhaber/angular-js-bootstrap-datetimepicker#130]
##### Bug description:

We moved to Angular 1.6.0 and unfortunately npm only has 2.0.1 of your module, resulting in us hitting the old version check code. Please publish 2.0.2 to npm

**Comment by zhaber** [comment]
Published https://www.npmjs.com/package/angular-ui-bootstrap-datetimepicker
