### ISSUE TITLE
Error: [ng:cpws] Can't copy! Making copies of Window or Scope instances is not supported

### ISSUE THREAD

**Issue by ncrocfer** [zhaber/angular-js-bootstrap-datetimepicker#132]
Hello,

I have a `ng:cpws` error using your this plugin and the yeoman [genenator](https://github.com/yeoman/generator-angular) :

![datepicker_angular](https://cloud.githubusercontent.com/assets/1552526/22145755/f5558678-df02-11e6-899e-08352b1ca9db.png)

I simply generate a new angular project :

**app/views/main.html**

    <datetimepicker data-ng-model="main.date" date-format="dd-MMM-yyyy"></datetimepicker>

**app/scripts/app.js**

    $routeProvider
          .when('/', {
            templateUrl: 'views/main.html',
            controller: 'MainCtrl',
            controllerAs: 'main'
          })
         .otherwise({
            redirectTo: '/'
          });
      });

**app/scripts/controllers/main.js**

    angular.module('nodejsApp')
      .controller('MainCtrl', function () {
        this.date = new Date();
      });

It does not work, with or without any custom options...

Do you have an idea please ?

**Comment by alexsk** [comment]
+1
The issue appears in angular v1.6.x. Angular v1.5.x works ok.

**Comment by zhaber** [comment]
I changed the way an inner form is isolated to fix the initialization issue.

**Comment by MGouaillier** [comment]
Hello, i'm also using this componnent and i'm confronted to the same issue. I've seen your update (isolateForm) and it's fixing the problem. 

My question is : When will you realease an updated version with this bug fix ?

Thanks for your time

**Comment by zhaber** [comment]
Updated plugin version

**Comment by c-amedicha** [comment]
I have the latest updated code but the issue still persists for angular version 1.6 or above .
![image](https://cloud.githubusercontent.com/assets/24658489/24304879/633379d8-1091-11e7-8926-2d5c5f343ee8.png)


Does any one else get the same issue with the latest plugin version?

**Comment by zhaber** [comment]
Do you have plunkr where we can reproduce it?

**Comment by c-amedicha** [comment]
Please find the Plunker here:
http://plnkr.co/edit/2jyyaQuiRmlfS18qZjz1?p=preview

**Comment by zhaber** [comment]
You can try the latest commit now. Plunker: http://plnkr.co/edit/qRhNlfTWlt9wIexa3WbB?p=preview

**Comment by c-amedicha** [comment]
Thank you for fixing it. It works well now!!
