### ISSUE TITLE
angular 1.6.4 validation problem

### ISSUE THREAD

**Issue by abdurahmanus** [zhaber/angular-js-bootstrap-datetimepicker#136]
Hi, I've tried to use datetimepicker with latest version of angular (1.6.4). And it returns error:
TypeError: ctrlCopy.$setValidity is not a function

**Comment by zhaber** [comment]
Are you using the [latest version](https://github.com/zhaber/angular-js-bootstrap-datetimepicker/blob/master/datetimepicker.js) of the plugin? Is there a [plunker](http://plnkr.co/edit/qRhNlfTWlt9wIexa3WbB?p=preview) we can try?

**Comment by abdurahmanus** [comment]
It looks good in plunker with angular 1.6.4. Maybe I did something wrong. I'll try it later in my project, thanks!
