### ISSUE TITLE
ng-required/ required not working with form.$invalid

### ISSUE THREAD

**Issue by anyayunli** [zhaber/angular-js-bootstrap-datetimepicker#140]
##### Bug description:
similar problems: https://github.com/zhaber/angular-js-bootstrap-datetimepicker/issues/98 & https://github.com/zhaber/angular-js-bootstrap-datetimepicker/issues/47
angular version 1.4.7, I am using the latest library. 
##### Link to minimally-working plunker that reproduces the issue: 
form.$invalid and form.$valid never gets updated: http://plnkr.co/edit/SAQYecYABzw0K1SK1VXg?p=preview

**Comment by KirillMedvedevGR** [comment]
I have similar problem. When I open the form with "required" empty datetimepicker and immediately submit the form, $invalid is still false. That's inconsistent with the rest of controls I use...

**Comment by anyayunli** [comment]
I made my own date and time picker directive in the end, it's a simple implementation,link here if someone needs similar functionalities: https://gist.github.com/anyayunli/d53c49528fcf4bbcb48f5795b501eb32

**Comment by zhaber** [comment]
Added support for the "required" attribute: http://plnkr.co/edit/qhBLDEV0O4fKhi1liDIi?p=preview

**Comment by KirillMedvedevGR** [comment]
@zhaber, thank you so much for fix! I've tried updating the package via bower, but it downloads previous version (without 'required'). Can you create a new version?

**Comment by zhaber** [comment]
Done
