### ISSUE TITLE
Problems using alongside ng-csp

### ISSUE THREAD

**Issue by mchapman** [zhaber/angular-js-bootstrap-datetimepicker#141]
When used with the ng-csp directive the datepicker doesn't open.  Furthermore, seconds become editable (in a pretty ugly way).

See [plunker](http://plnkr.co/edit/cxeFMf?p=preview) - only difference from demo in readme is the ng-csp.

**Comment by zhaber** [comment]
Caused by uib-timepicker that does not support ng-csp (issue tracker https://github.com/angular-ui/bootstrap/issues )

http://plnkr.co/edit/Mzus58UeY5Gc7sjavy7n?p=preview

**Comment by mchapman** [comment]
Not sure you are right, but you prompted me to look a bit further and I came across https://github.com/angular-ui/bootstrap/issues/6419.  Adding the [CSS](https://github.com/angular-ui/bootstrap/blob/master/src/datepickerPopup/popup.css) fixes the pop-up issue but not the seconds input (which I don't actually get in my app anyway).  Perhaps you should add the css to yours?  I could submit a PR but I suspect you will do it 5 times as fast.

**Comment by zhaber** [comment]
I updated the issue you referenced with timepicker behavior, however, according to README in the main project, it was closed and new requests are not accepted.

**Comment by mchapman** [comment]
I was suggesting that you add the CSS from https://github.com/angular-ui/bootstrap/blob/master/src/datepickerPopup/popup.css to https://github.com/zhaber/angular-js-bootstrap-datetimepicker/blob/master/datetimepicker.css.  That will provide a partial (at least) fix I think.

**Comment by zhaber** [comment]
This css is one of angular-ui dependencies, so if you use a depedency manager such as npm it should already be in your project file tree.
