### ISSUE TITLE
Also allow readonly date input field like readonly-time option

### ISSUE THREAD

**Issue by Pranab16** [zhaber/angular-js-bootstrap-datetimepicker#49]

**Comment by zhaber** [comment]
It was possible with the ng-disabled attribute before. I replaced it with "readonly-date" to clear separation between date and time values: http://plnkr.co/edit/QujX5A?p=preview

**Comment by zhaber** [comment]
You can also use the hidden-date property: http://plnkr.co/edit/zJOc40?p=preview
