### ISSUE TITLE
Disable timepicker display

### ISSUE THREAD

**Issue by atnonis** [zhaber/angular-js-bootstrap-datetimepicker#51]
Is there an option to disable the timepicker display?

**Comment by romangrb** [comment]
Can we disable ?

**Comment by zhaber** [comment]
See `readonly-time` https://github.com/zhaber/angular-js-bootstrap-datetimepicker

**Comment by zhaber** [comment]
You can also use the hidden-time property: http://plnkr.co/edit/zJOc40?p=preview
