### ISSUE TITLE
Unable to get initDate in  date-options to work

### ISSUE THREAD

**Issue by bondseid** [zhaber/angular-js-bootstrap-datetimepicker#52]
Hello,

i have experimented with the directive for a few hours. 

Everything works well, except that i am trying to set the initDate property of the default datepicker through the date-options parameter.

<datetimepicker
              data-ng-model="aceModel"
              data-minute-step="config.minuteStep"
              data-min-date="config.minDate"
              data-max-date="config.maxDate"
              data-date-options="options"
              date-format="dd-MMM-yyyy"></datetimepicker>

$scope.options = {
       initDate: new Date(2011, 11, 1)
}

It seems to be ignored completely.

Thanks for the directive though, very nice.

**Comment by zhaber** [comment]
The initial date is set via ng-model. See an example at http://plnkr.co/edit/QujX5A?p=preview

**Comment by bondseid** [comment]
Ok yes this is what i have done.

One other issue i am having. I am using angular 1.4 . To get changes i am doing a $scope.$watch on my date object which is bound to the ng-model.

The model is not updated when changing the time, only the date.

**Comment by lpalnau** [comment]
I second the issue of changing the time not updating the model (does not trigger my $watch). I was on an older version locally that didn't seem to have the issue and our CI server was on 0.11.2 and it is having the issue. Updating my local to 0.12.0 now I see the issue locally too.

**Comment by lpalnau** [comment]
I took another peek at this, and I was a little inaccurate, it looks like the model property does get updated when changing the time, but it does it in a way that my $watch can't detect. Going to take a peek at the directive source to see if there is a missing $apply.

A workaround for me is to use a $watch and a ng-click attrib on the directive to call the same controller method for now.

**Comment by zhaber** [comment]
Are you using object equality for watch https://docs.angularjs.org/api/ng/type/$rootScope.Scope#$watch ?

**Comment by lpalnau** [comment]
No, I'm not specifying it and I believe it defaults to false, since it is
optional. Do you think setting object equality to true will cause the watch
to fire when the time controls are used to change the time?

-Luke
734.604.2271

On Mon, Aug 10, 2015 at 7:28 PM, Vitalii Fedorenko <notifications@github.com

**Comment by zhaber** [comment]
Setting the object equality parameter to true should do the trick
