### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by necroscope** [zhaber/angular-js-bootstrap-datetimepicker#53]
Thank you for such an awesome date time picker. I have a question I wanted to have two of these on one html page. One for the start date of an event and one for the stop date of an event.  Could you please provide any pointers.  I was thinking I need examples.js and examples2.js.  What are your thoughts? Please assist if you get a second.  It would be very appreciated!

Thanks again!

**Comment by zhaber** [comment]
There is  no example like that in the repository at the moment but it seems like a one that would be useful to have. Please feel free to submit a pull request with a sample start/end component if you want.
