### ISSUE TITLE
readonly-time doesn't disable the time picker

### ISSUE THREAD

**Issue by pguegan** [zhaber/angular-js-bootstrap-datetimepicker#55]
Hi,
Using the latest version (0.12.0) and Angular 1.4.4, it seems the attribute `readonly-time` is not working at all. Here is an example:

```html
<datetimepicker ng-model="form.begin"
    max-date="form.end"
    minute-step="5"
    show-meridian="false"
    date-format="dd/MM/yyyy"
    placeholder="jj/mm/aaaa"
    readonly-time="true">
```

Despite the attribute `readonly-time="true"`, the time picker is still enabled. Is there a workaround I could use to make this possible?

Thanks a lot.

**Comment by zhaber** [comment]
Are you able to reproduce it in the latest revision of the datetimepicker? 
http://plnkr.co/edit/QujX5A?p=preview

**Comment by pguegan** [comment]
You're right: #54 solves this issue.

As this new revision isn't available yet _via_ Bower or Rails Assets, I just picked up the file from master.

Thank you for your great job :)
