### ISSUE TITLE
issue when changing the date

### ISSUE THREAD

**Issue by gvandenbosch** [zhaber/angular-js-bootstrap-datetimepicker#57]
I have some weird issue, I followed the example.js from plunker.

All goes fine when display the date as:

     {{date | date:'shortTime' }}, {{date | date:'fullDate' }}

When I use a submit button in my form and try to grab date and time and display in an alert like this:
 
    alert($scope.date.toString());  

It works when I am changing the time, the alert updates the time.
However when I change the date it keeps stuck at the initial date and also if I change the time after it doesn't update anymore.

What could be causing this?

**Comment by zhaber** [comment]
Do you have a plunker code sample?

**Comment by gvandenbosch** [comment]
It's solved now, once I started to put it in plunker I discovered I made a stupid mistake by wrongly including the controller. This can be closed.
