### ISSUE TITLE
Does it support the Glyphicons Halflings.

### ISSUE THREAD

**Issue by hsubbarao** [zhaber/angular-js-bootstrap-datetimepicker#58]
Hello,

I am facing some issues using this datetime pickerin firefox. The same code works well in crome. 
It has this Glyphicons Halflings not found issues.

in forefox it give me a 404 error with following file.
glyphicons-halflings-regular.woff
glyphicons-halflings-regular.ttf

Network error file not found.

I am raising this issue from home once i reach office and can access the lab will append the exact error and snapshot as well.
i have added the cdn link the way it is given in the example index.html as well

will appreciate a quick response.
Thanks in advance
Harsha

**Comment by hsubbarao** [comment]
I am back in office. I am attaching the screen shot of the image. 
<img width="1439" alt="screen shot 2015-09-23 at 8 44 32 am" src="https://cloud.githubusercontent.com/assets/13416304/10037145/9c7a58e6-61cf-11e5-959e-79a2bc62b966.png">

**Comment by zhaber** [comment]
Does http://angular-ui.github.io/bootstrap/ Datepicker work for you in firefox?

**Comment by zhaber** [comment]
Closing as no response was provided.
