### ISSUE TITLE
Disable spinners

### ISSUE THREAD

**Issue by swrocket** [zhaber/angular-js-bootstrap-datetimepicker#59]
The original timepicker allows you to hide the spinners by setting show-spinners to false.
For some reason, this doesn't work on this control.
I tried adding it into the directive (wherever showMeridian is I added showSpinners) but no joy.

Any ideas?

TIA

Andrew

**Comment by zhaber** [comment]
Here is a working example: http://plnkr.co/edit/z1sKPT?p=preview (not in the repository yet)
A pull request is welcome.

**Comment by swrocket** [comment]
Thanks zhaber, work now. I had the wrong version of ui-bootstrap too which caused it to fail
