### ISSUE TITLE
Mobile support

### ISSUE THREAD

**Issue by mrgcohen** [zhaber/angular-js-bootstrap-datetimepicker#61]
Does this degrade nicely on mobile?

**Comment by zhaber** [comment]
You can test the plugin by opening http://run.plnkr.co/8qRfEvexNhkupRZB/ from a mobile device or emulation software.

**Comment by mrgcohen** [comment]
Yeah. It's hard to see. I tested on phone.

**Comment by zhaber** [comment]
Do you have a link to an environment where I can reproduce the problem? And, do you experience the same issues with https://angular-ui.github.io/bootstrap/ date and time widgets?
