### ISSUE TITLE
ngModel binding is not working in TabSet

### ISSUE THREAD

**Issue by actolap** [zhaber/angular-js-bootstrap-datetimepicker#62]
http://plnkr.co/edit/ty2JAR?p=preview

Watch is not getting called:

$scope.$watch("date", function(value) {
      console.log('New date value:' + value);
}, true);

**Comment by zhaber** [comment]
`date` variables are created within an isolated scope in Angular UI tabs:
http://stackoverflow.com/questions/15752577/getting-the-scope-within-angular-ui-tabs
