### ISSUE TITLE
Is there an option to disable time?

### ISSUE THREAD

**Issue by someone235** [zhaber/angular-js-bootstrap-datetimepicker#63]
Something like `<datetimepicker show-time="false"></datetimepicker>`

**Comment by zhaber** [comment]
Yes, there is a way to disable time (see the Readme).

**Comment by someone235** [comment]
Sorry, I don't find it. What is the name of the attribute?

**Comment by zhaber** [comment]
`readonly-time` disables the time, if you want to remove it completely use datepicker from Angular UI

**Comment by zhaber** [comment]
You can also use the hidden-time property on this directive: http://plnkr.co/edit/zJOc40?p=preview
