### ISSUE TITLE
How to change the datetimepick language ?

### ISSUE THREAD

**Issue by my9074** [zhaber/angular-js-bootstrap-datetimepicker#64]
What I use is Chinese, how to change language? 3Q～

**Comment by zhaber** [comment]
Just add the localized js file in the header of your page: http://plnkr.co/edit/ZrfDlSROZxKrOAiA0PXp?p=preview

**Comment by my9074** [comment]
@zhaber  This code ??? 
```
<script src="http://code.angularjs.org/1.0.8/i18n/angular-locale_fr-fr.js"></script>
```

**Comment by zhaber** [comment]
yup
