### ISSUE TITLE
Display only time

### ISSUE THREAD

**Issue by Seiifer** [zhaber/angular-js-bootstrap-datetimepicker#68]
Is there a way to use it as a time picker only ?
I want to remove the date, not make it disabled but only have the time picker left.

**Comment by Seiifer** [comment]
Nvm in that case, `  <uib-timepicker>` is the standalone solution.

**Comment by zhaber** [comment]
You can also use the hidden-date property on this directive: http://plnkr.co/edit/zJOc40?p=preview
