### ISSUE TITLE
type a letter on the date field and it crashes

### ISSUE THREAD

**Issue by luisgarciaalanis** [zhaber/angular-js-bootstrap-datetimepicker#69]
need to check that the input is a valid date before assigning the value to the time variable on the link function of the directive:

something like this.

                            newTime = new Date(newTime);

                            if (isNaN(newTime.getTime()) == false) {
                                scope.time = newTime; // change the time
                                if (firstTimeAssign) {
                                    firstTimeAssign = false;
                                }
                            }

**Comment by zhaber** [comment]
Pull request?

**Comment by zhaber** [comment]
Related commit: https://github.com/zhaber/angular-js-bootstrap-datetimepicker/commit/0b573c2255e69818c736bdd3b44aa6126073eb6d
