### ISSUE TITLE
typing letter and invalid numbers on the timepicker

### ISSUE THREAD

**Issue by luisgarciaalanis** [zhaber/angular-js-bootstrap-datetimepicker#70]
There is no way to validate this and set the directive to a bad state so that forms can prevent post?

it would also be nice to add a property to the directive to set readonly-input=true on the time witget and the date widget, that way the user can't mess up the values while its broken. but they can still use the mouse

**Comment by zhaber** [comment]
A form that contains the datetime element is marked as invalid in this case, see http://plnkr.co/edit/zJOc40?p=preview
