### ISSUE TITLE
Browser compatibility

### ISSUE THREAD

**Issue by hsubbarao** [zhaber/angular-js-bootstrap-datetimepicker#71]
Hello,

Does this work consistently on all browsers.

I am having issues with firefox and safari as well. Works only chrome.

Please comment. this is  a little urgent.

Thanks
Harsha

**Comment by zhaber** [comment]
It is a cross-browser plugin built on top of the Bootstrap library. Please also check whether you experience the same issues with [Angular UI](https://angular-ui.github.io/bootstrap/) as this module just wraps date and time picker from this library.

**Comment by hsubbarao** [comment]
Thanks.  Now this is working.  Added the below entry in index.html explicitly.

 <script src="bower_components/angular-ui-bootstrap-datetimepicker/datetimepicker.js"></script> 

This was not getting picked up when i used grunt to build the dist directory. 
 So once you add this explicit entry it works.

**Comment by hsubbarao** [comment]
please close this issue in case this is the way to solve this issue.
