### ISSUE TITLE
Error: [$rootScope:inprog] $digest already in progress

### ISSUE THREAD

**Issue by hsubbarao** [zhaber/angular-js-bootstrap-datetimepicker#72]
Hello,

when i click on the datetimepicker this is the error i get in console. 
I have not used any $digest , watch anywhere in my code. so i have no clue why this error comes up. 
it also says too much recursion. 
will add all the details once you respond.
Thanks.
Harsha

**Comment by zhaber** [comment]
Can you reproduce this error at http://plnkr.co/edit/zJOc40?p=preview ?
