### ISSUE TITLE
Some attributes don't work

### ISSUE THREAD

**Issue by iredjee** [zhaber/angular-js-bootstrap-datetimepicker#74]
`hidden-time`,  `starting-day`, and maybe some other attributes (I didn't check them all) don't work

**Comment by zhaber** [comment]
Which version of angularjs and angularjs bootstrap UI are you using? You can experiment with the hidden-time attribute at http://plnkr.co/edit/zJOc40?p=preview As far as the second attribute is concerned, it appears that in the current version of the datepicker the starting day should be configured from the dateOptions attribute (I removed the attribute from readme so it's not misleading). Related issue: https://github.com/angular-ui/bootstrap/issues/768

**Comment by iredjee** [comment]
I found out that bower version is differ than github version of file. I tried the following  
`bower install angular-ui-bootstrap-datetimepicker`  
and   
`bower install https://github.com/zhaber/angular-js-bootstrap-datetimepicker.git`  
But I guess both of them download older version of file. Could you pls check it out? Thanks.

**Comment by zhaber** [comment]
Released the new version: https://github.com/zhaber/angular-js-bootstrap-datetimepicker/releases/tag/v0.14.3

**Comment by iredjee** [comment]
Thanks a lot. I close this issue.
