### ISSUE TITLE
Validation attributes do not persist.

### ISSUE THREAD

**Issue by Cyricx** [zhaber/angular-js-bootstrap-datetimepicker#75]
For example the name="" or required

**Comment by Cyricx** [comment]
I apologize, the required is carrying through, however the name is not, so it breaks standard validation, and unfortunately I do not see a way to wire up min and max validation between two inputs

**Comment by zhaber** [comment]
I added support for the datepicker validation based on the name attribute, see http://plnkr.co/edit/zJOc40?p=preview To set min and max you will need to create deep watchers on two model objects .
