### ISSUE TITLE
Not same time 

### ISSUE THREAD

**Issue by KaungMyatAung** [zhaber/angular-js-bootstrap-datetimepicker#77]
Hello zhaber.
I have some problem.
When i save date with time in my database,date is match in my database but time is not match that i choose.When i select time to 7:00 AM it save 12:30 AM in my database.

**Comment by zhaber** [comment]
What time is in your model variable? Do you have a plunker handy that reproduces the issue?

**Comment by KaungMyatAung** [comment]
Sorry Bro this is my false.Now i'm fine.Thank you bro.
