### ISSUE TITLE
automatically close one datepicker popup when opening another datepicker instance

### ISSUE THREAD

**Issue by JackGommeren** [zhaber/angular-js-bootstrap-datetimepicker#79]
When i have two or more directives of a datetimepicker on a page and when i have openend one, I want it to automatically close the other. This is not the case in the current version as it leaves the other one open as it opens yet another datepicker popup.

Perhaps it would be best to have this option as a global (and local) setting on each directive for the instances that you do want to have multiple opened datepickers on one page.

The screenshot below illustrates the issue, I want only one instance of a datepicker to be openend at a time, not multiple:
![multiple datepickers overlap](https://cloud.githubusercontent.com/assets/14069393/12173130/51420426-b555-11e5-88b9-2a63624cfc32.JPG)

**Comment by zhaber** [comment]
Datetimepicker wraps Angular UI Bootstrap Datepicker developed under https://github.com/angular-ui/bootstrap Please feel free to submit an issue there.

**Comment by JackGommeren** [comment]
I feel this is not a functionality which should come in the Angular UI Bootstrap Datepicker by default. When using the default datepicker, and opening a second datepicker,.. you can automatically close the first datepicker by using the following solution in the controller (which in the case of this plugin, resides inside of the plugin):

HTML:
<div class="form-horizontal pull-left">
                <input type="text" datepicker-popup="dd-MMMM-yyyy" ng-model="dt" is-open="opened" min="minDate" max="'2015-06-22'" datepicker-options="dateOptions" date-disabled="disabled(date, mode)" ng-required="true"/>
                <button class="btn" ng-click="open()"><span class="glyphicon glyphicon-calendar"></span></button>
            </div>
            <div class="form-horizontal pull-left">
                <input type="text" datepicker-popup="dd-MMMM-yyyy" ng-model="dt" is-open="opened" min="minDate" max="'2015-06-22'" datepicker-options="dateOptions" date-disabled="disabled(date, mode)" ng-required="true" />
                <button class="btn" ng-click="open()"><span class="glyphicon glyphicon-calendar"></span></button>
            </div>

JS (to be modified in the controller):

$scope.open = function($event,opened) {
   $event.preventDefault();
   $event.stopPropagation();
   $scope[opened] = true;
};

http://stackoverflow.com/questions/19613510/how-to-have-at-least-two-datepickers-of-ui-bootstrap-on-a-single-page

I cannot modify the specific html attributes (ng-click) of the datepicker itself nor the controller for just the datepicker to make this change.

**Comment by zhaber** [comment]
See the last commit: https://github.com/zhaber/angular-js-bootstrap-datetimepicker/commit/2c7d772fe11a882930f378bcef0d32ce84307e29 and plunkr at http://plnkr.co/edit/zJOc40?p=preview
