### ISSUE TITLE
Local Time Zone cann't show on Firefox.

### ISSUE THREAD

**Issue by KaungMyatAung** [zhaber/angular-js-bootstrap-datetimepicker#80]
Hi.
I cann't show local time zone in the text box on firefox.But on chrome,the return datetime is show 
local time zone datetime.
Here is my code for edit datetime again.

           <datetimepicker ng-model="Event.eventStartDate"
                            date-format="dd-MMM-yyyy"
                            date-options="dateOptions">
            </datetimepicker>

Which code can i missing?

**Comment by zhaber** [comment]
Local time zone support can be tracked in the datepicker backlog at https://github.com/angular-ui/bootstrap/issues/4837
