### ISSUE TITLE
IE11 does not support XPath required at line 169 in datatimepicker.js

### ISSUE THREAD

**Issue by RichardCroxall** [zhaber/angular-js-bootstrap-datetimepicker#82]
The following code at line 169 in datatimepicker.js relies on Xpath.
        link: function(scope, element, attrs, ctrl) {
          var firstTimeAssign = true;

          scope.$watch(function() {
            return scope.ngModel;
          }, function(newTime) { 
            var timeElement = document.evaluate("//*[@ng-model='time']", 
                element[0], null, XPathResult.FIRST_ORDERED_NODE_TYPE, null).singleNodeValue

I get an error message from the console in IE11.
The following site claims that IE does not support XPATH.
http://stackoverflow.com/questions/23560438/xpathresult-is-undefined-in-ie11
It suggests use of CSS selects instead (though I don't know whether that is possible).

**Comment by RichardCroxall** [comment]
I might have left this comment against the wrong dateTimePicker?

**Comment by zhaber** [comment]
Unfortunately, Internet Explorer is not supported by this plugin. Microsoft Edge adds support for XPath.
