### ISSUE TITLE
minDate setting does not disable past time for the first selectable day

### ISSUE THREAD

**Issue by JulioDeL** [zhaber/angular-js-bootstrap-datetimepicker#85]
Hello,

I think this will be easier to understand with an example rather tan verbose explanation:

If I set min-date as February 1st 11:00:00 am, I'm able to  select February 1st 10:00:00. In this case I would expect 11:00:00 to be the minimum pickable time and not be able to select a past time.

I don't see in the documentation a parameter for setting the minimum selectable time, so I supposed minDate would do the trick, but it doesn't for this particular scenario.

I would appreciate if you please let me know if this issue will be fixed or there exists a workaround to lock past times (I might be missing something..).

Thank you.

**Comment by zhaber** [comment]
The last commit applies minDate to timepicker as well.

**Comment by JulioDeL** [comment]
Thank you for taking a look at this issue, but it doesn't seem to be completely fixed yet. Now the time picker is always locked and I can't select a different hour and/or minute. 

I get the following error whenever the datetime picker is rendered or I switch between the date and time modals: 

`TypeError: b.getFullYear is not a function at Scope.j.compare`

Also, I don't know if this has something to do, but I'm passing a moment.js object as the minDate value:

`$scope.dateTimePickerOptions = {
          minDate: moment().valueOf()
        }`

**Comment by zhaber** [comment]
Does this plunker work for you? http://plnkr.co/edit/LJCTeX?p=preview

**Comment by JulioDeL** [comment]
Yes it does.

**Comment by zhaber** [comment]
moment.js values are not supported by the plugin at the moment

**Comment by y4nnL** [comment]
Hello
The plunker does not work for me.
If I set the time picker to 01:00AM of today and then select the minimum date (yesterday) in the date picker. The time picker turns red which is OK. But then if I set 01:01AM by pressing the up key (I can't go down) into the minutes field, or by clicking the up spinner, it turns immediately "green" and $valid is true

**Comment by zhaber** [comment]
For some reason, this line https://github.com/zhaber/angular-js-bootstrap-datetimepicker/blob/master/datetimepicker.js#L211 returns an empty list of errors for the timepicker in the last step. Please create a separate issue for this problem.

**Comment by y4nnL** [comment]
This line can be involved in the fact that "$pristine": true, "$dirty": false never change as I modify the form (manually or via the UI)?
