### ISSUE TITLE
Colliding module name with other ui.bootstrap.datetimepicker

### ISSUE THREAD

**Issue by MacGyver27** [zhaber/angular-js-bootstrap-datetimepicker#88]
Hey,

Please change your angular module name, it is already colliding with this module: bootstrap-ui-datetime-picker @ https://github.com/Gillardo/bootstrap-ui-datetime-picker

Thanks, Michal

**Comment by zhaber** [comment]
This module was created in October 2013: https://github.com/zhaber/angular-js-bootstrap-datetimepicker/commit/6daacdcea9c549abb12314c6075f857cb3df3d85#diff-11e8d851f57265d26823b90c8f465a4c
