### ISSUE TITLE
TypeError: this.activeDate.getFullYear is not a function

### ISSUE THREAD

**Issue by snkhan** [zhaber/angular-js-bootstrap-datetimepicker#89]
When using with 1.5.0 Angularjs with 1.1.2/ui-bootstrap-tpls.min.js 

The formatting seems not setting and also date is not set

Regards

**Comment by zhaber** [comment]
This plunker http://plnkr.co/edit/LJCTeX?p=preview uses Angular 1.5 and UI Bootstrap 1.1.2. Both the date format and value are updated.
