### ISSUE TITLE
Updated model is not properly reflected into datetimepicker view

### ISSUE THREAD

**Issue by MacGyver27** [zhaber/angular-js-bootstrap-datetimepicker#90]
Hey,

Great module! very useful. However I have issue to report.

Please check the following plunkr: http://plnkr.co/edit/f8y6bIhqxxFf6kS9s3Is?p=preview

What I want to achieve is:
1) Define changeStart and changeEnd by the user manually on the view and have:
2) updated impactStart and impactEnd using angular $watch

When manipulating "minutes:seconds" part of changeStart, impactStart model gets changed but it is not reflected in the datetimepicker view.

Strange thing is it works for the second "End" part (changeEnd -> impactEnd).. I was debuging for some hours and could not fix this..

When you manipulate "date" part it works nice, it is just when "minutes and seconds" are adjusted it doesnt work for the "start" part, but for the "end" part it somehow works..

Thank you and appreciate any input. Michal

**Comment by MacGyver27** [comment]
Hey,

Just FYI this bug can be overcome placing some fake datetimepicker and hide it on the view..
`<datetimepicker ng-model="testFake" ng-hide="true"></datetimepicker>` and rest of the datetimepickers on the view work as expected: http://plnkr.co/edit/DKec0wRsYdzQFkMF3NWJ?p=preview

Thanks, Michal

**Comment by zhaber** [comment]
Fixed in https://github.com/zhaber/angular-js-bootstrap-datetimepicker/commit/d906368d9a2e75fe9dc6bc4daa0bf01f229a4c00
