### ISSUE TITLE
min-date and max-date are not updated into the view when model is changed

### ISSUE THREAD

**Issue by MacGyver27** [zhaber/angular-js-bootstrap-datetimepicker#91]
Hey,

Me again. What I found out is that min-date and max-date are not updated into the view when model is changed using **minutes:seconds** fields. When model is changed programmatically or using **date** field, min, max gets reflected..

Your **minutes:seconds** updates the model, but it is missing something to secure/do what is being done when the model value is changed programmatically.

Plunker where it works for ui-bootstrap and not so much using **minutes:seconds** field in your directive: http://plnkr.co/edit/R4ThtuNkzs8T2XGPwAZ3?p=preview

Thank you, Michal

**Comment by zhaber** [comment]
- Did you try to reproduce this problem with the latest version of the directive? I've made some changes to the way min/max dates are handled, which may also affected your issue.
- Does this problem still exist if you use just the underlying timepicker from http://angular-ui.github.io/bootstrap/#/timepicker and min/max attributes?
- What are the exact steps to reproduce this issue?

**Comment by MacGyver27** [comment]
Hey,
Updated to most recent version at both sides (uib and yours).
http://plnkr.co/edit/b41fHQHnRkrxG1qNl1i9?p=preview

problems:
a) - increase changeEnd by 1 hour -> impactEnd is not allowed to reach its maximum, which is configured to be changeEnd.
b) - increase changeEnd till it goes over midnight -> impactEnd max/min restrictions are completely messed up
c) - decrease changeStart either by hour or minute -> impactStart is marked as invalid for the time field (date part seems still valid)
d) - decrease changeStart either by hour or minute -> impactStart is not allowed to reach its minimum, which is configured to be changeStart.
e) - go over midnight backwards at time field for changeStart -> impactStart is then allowed to be lover its minimum which is defined to be changeStart.

Based on the spooky behavior mentioned above there is definitely something wrong..

Thanks for looking into it, Michal

**Comment by zhaber** [comment]
It appeared that angular ui timepicker min/max attribute watchers do not use deep watch, thus the changes were not propagated downstream. Which of these items are still relevant in release 1.2.4?https://github.com/zhaber/angular-js-bootstrap-datetimepicker/releases/tag/1.2.4
