### ISSUE TITLE
Update for UI Bootstrap 1.2.1

### ISSUE THREAD

**Issue by davemoore24** [zhaber/angular-js-bootstrap-datetimepicker#93]
Console warnings:
- uib-datepicker settings via uib-datepicker-popup attributes are deprecated and will be removed in UI Bootstrap 1.3, use datepicker-options attribute instead
- uib-datepicker minDate attribute usage is deprecated, use datepicker-options attribute instead

**Comment by zhaber** [comment]
Fixed in https://github.com/zhaber/angular-js-bootstrap-datetimepicker/commit/8e8db003b38710f7433985964ef6363c36d6909b
