### ISSUE TITLE
$parse:syntax when using ui-bootstrap 1.1.2

### ISSUE THREAD

**Issue by Robin-Hoodie** [zhaber/angular-js-bootstrap-datetimepicker#97]
After spending a few hours on this I thought I'd save people in the same situation as me some time. Using `ui-bootstrap` version 1.1.2 will give the above error, here is a [plunkr](http://plnkr.co/edit/BBlpQE?p=preview) forked off the main demo changing the version to 1.1.2, check the console for the error. This will also cause the calendar picker not to open.

**Comment by zhaber** [comment]
Thanks, changed the recommended version of angular bootstrap to 1.2.4
