### ISSUE TITLE
$touched and $dirty never set on the input, $required is only set after having had a previous value

### ISSUE THREAD

**Issue by Robin-Hoodie** [zhaber/angular-js-bootstrap-datetimepicker#98]
See this [plunkr](http://plnkr.co/edit/ZcVLv2?p=preview). The `$touched` and `$dirty` flag never seem to be set. Also, when adding `required` and starting off with an empty value the `$required` error is not set. However, when filling in a value and then removing it, it is set correctly.

**Comment by zhaber** [comment]
Changed the controller to propagate $dirty and $touched values.

**Comment by Robin-Hoodie** [comment]
Neat, thanks for taking care of this so quickly
