### ISSUE TITLE
Does not load correctly

### ISSUE THREAD

**Issue by cidthecoatrack** [zhaber/angular-js-bootstrap-datetimepicker#99]
Hello, I have been using your date time picker for a while, and all of a sudden, it no longer loads correctly.  Here is the code that I try to use:

```csharp
<div class="form-group col-sm-4">
    <label for="scheduledDateInput">Date and Time Found</label>
    <datetimepicker id="scheduledDateInput" ng-model="vm.scheduledDate" ng-required="true" hour-step="1" minute-step="1" show-meridian="true" date-format="dd-MMM-yyyy"></datetimepicker>
</div>
```

And here is what shows in my UI:

![image](https://cloud.githubusercontent.com/assets/2846466/14370360/7d44a018-fcfb-11e5-9e4e-02135c2d51ab.png)

No time section loads at all, the label should be a line above the control (no longer is), and the date section is chopped off.  It does not respect the format specified in the code.  I thought it might be a javascript load error, but no javascript errors are being thrown.  I am loading the javascript file, I have marked the module as a dependency, and I cannot figure out why it won't load correctly anymore.  It was working for a long time, and has only recently stopped.

Please help.

**Comment by zhaber** [comment]
Do you have a plunker that reproduces the problem? Here is the latest version of the plugin: http://plnkr.co/edit/HyGjgy?p=preview

**Comment by ostranme** [comment]
Make sure you have the latest version of Angular UI bootstrap. I have found if you use previous versions it will throw UI errors like you are seeing. Try updating to v1.3.1 if you haven't already.

https://cdnjs.com/libraries/angular-ui-bootstrap

**Comment by cidthecoatrack** [comment]
@ostranme - I am using 1.3.1.

**Comment by cidthecoatrack** [comment]
@zhaber [Here](http://plnkr.co/edit/n8chyWnAKOEDxw0WsNpd?p=preview) is a plunk that replicates the problem.  There are a lot of dependencies in my app, so I tried to whittle this plunk down.  However, it does show the bug occurring: the fields are **Date & Time Found** and **Date & Time Claimed**.

**Comment by cidthecoatrack** [comment]
I will also note I had to trim a lot of excess code for the plunkr.  There shouldn't be any build errors or mistakes - but there is always the chance.

**Comment by ostranme** [comment]
Looks like the version of the datetimepicker.js was old or different. I added a different version titled datetimepicker-new.js and commented out your script in the head. Looks like its working with this version.

http://plnkr.co/edit/ETnnfsLb7ArdnIbCUvN6?p=preview

**Comment by cidthecoatrack** [comment]
Interesting. I am using he newest from nuget, which is version 0.11. Is
that the correct version?

**Comment by ostranme** [comment]
looks like its v1.2.4 is the latest version in @zhaber's bower and npm packages

**Comment by cidthecoatrack** [comment]
I copied the new `datetimepicker.js`, and everything works again.  I don't know why the NuGet package is so out o date, but it should be updated.

**Comment by ostranme** [comment]
Good to hear, glad it works now!

**Comment by zhaber** [comment]
The latest version of the nuget package can be found at https://www.myget.org/feed/Packages/angular-js-bootstrap-datetimepicker
